#DB Gabia ver (for Windows)
db.driver.Class=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://my8003.gabiadb.com:3306/hkcodedb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
db.username=hkcode
db.password=fintech1308!